import dotenv from "dotenv";
import { z } from "zod";

dotenv.config({ path: "../.env" });
dotenv.config();

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]),
  BACKEND_PORT: z.coerce.number().int().positive(),
  BACKEND_HOST: z.string().default("0.0.0.0"),
  FRONTEND_URL: z.string().min(1).default("http://localhost:3000"),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  JWT_ALGORITHM: z.literal("HS256"),
  JWT_SECRET_KEY: z.string().min(32),
  JWT_REFRESH_SECRET_KEY: z.string().min(32),
  ACCESS_TOKEN_EXPIRE_MINUTES: z.coerce.number().int().positive(),
  ACCESS_TOKEN_COOKIE_NAME: z.string().min(1),
  REFRESH_TOKEN_EXPIRE_DAYS: z.coerce.number().int().positive(),
  REFRESH_TOKEN_COOKIE_NAME: z.string().min(1),
  COOKIE_SECURE: z.coerce.boolean(),
  COOKIE_HTTP_ONLY: z.coerce.boolean(),
  COOKIE_SAMESITE: z.enum(["lax", "strict", "none"]),
  BCRYPT_SALT_ROUNDS: z.coerce.number().int().positive(),
  SEED_TEACHER_EMAIL: z.string().email(),
  SEED_TEACHER_PASSWORD: z.string().min(8),
  SEED_STUDENT_EMAIL: z.string().email(),
  SEED_STUDENT_PASSWORD: z.string().min(8),
  SEED_ADMIN_EMAIL: z.string().email(),
  SEED_ADMIN_PASSWORD: z.string().min(8),
  OPENAI_API_KEY: z.string().min(1),
  GEMINI_API_KEY: z.string().min(1),
  OPENROUTER_API_KEY: z.string().min(1),
  OPENAI_MODEL: z.string().min(1),
  OPENAI_EMBEDDING_MODEL: z.string().min(1),
  GEMINI_MODEL: z.string().min(1),
  OPENROUTER_MODEL: z.string().min(1),
  ANTHROPIC_MODEL: z.string().min(1),
  OPENROUTER_BASE_URL: z.string().min(1),
  GEMINI_BASE_URL: z.string().min(1),
  LLM_CHEAP_PROVIDER: z.enum(["openai", "gemini", "openrouter"]),
  LLM_PREMIUM_PROVIDER: z.enum(["openai", "gemini", "openrouter"]),
  LLM_TEMPERATURE: z.coerce.number().min(0).max(2),
  LLM_MAX_TOKENS: z.coerce.number().int().positive(),
  LLM_OUTLINE_MAX_RETRIES: z.coerce.number().int().positive(),
  LLM_SLIDE_MAX_RETRIES: z.coerce.number().int().positive(),
  LLM_USE_FALLBACK: z.coerce.boolean(),
  LLM_CIRCUIT_BREAKER_THRESHOLD: z.coerce.number().int().positive(),
  LLM_CIRCUIT_BREAKER_COOLDOWN_MS: z.coerce.number().int().positive(),
  CACHE_SIMILARITY_THRESHOLD: z.coerce.number().min(0).max(1),
  EMBEDDING_PROVIDER: z.enum(["local", "openai"]),
  EMBEDDING_DIMENSIONS: z.coerce.number().int().positive(),
  QUEUE_CONCURRENCY: z.coerce.number().int().positive(),
  PRESENTATION_QUEUE_NAME: z.string().min(1),
  JOB_RETRY_ATTEMPTS: z.coerce.number().int().positive(),
  JOB_RETRY_DELAY_MS: z.coerce.number().int().positive(),
  JOB_PROGRESS_STEP_DELAY_MS: z.coerce.number().int().positive(),
  PPT_PUBLIC_BASE_URL: z.string().min(1),
  POLLING_INTERVAL_MS: z.coerce.number().int().positive(),
  MAX_REQUEST_BODY_BYTES: z.coerce.number().int().positive(),
  GENERATE_TOPIC_MIN_LENGTH: z.coerce.number().int().positive(),
  GENERATE_TOPIC_MAX_LENGTH: z.coerce.number().int().positive(),
  GENERATE_SUBJECT_MIN_LENGTH: z.coerce.number().int().positive(),
  GENERATE_SUBJECT_MAX_LENGTH: z.coerce.number().int().positive(),
  GENERATE_SLIDES_MIN: z.coerce.number().int().positive(),
  GENERATE_SLIDES_MAX: z.coerce.number().int().positive(),
  GENERATE_GRADE_MIN: z.coerce.number().int().positive(),
  GENERATE_GRADE_MAX: z.coerce.number().int().positive()
});

export const env = envSchema.parse(process.env);
